### ISSUE TITLE
DO NOT DOWNLOAD THIS, IT IS TROJAN

### ISSUE THREAD

**Issue by Opencode101** [DaddyLazarus/AdBot#3]
![image](https://github.com/DaddyLazarus/AdBot/assets/112879321/a74b24cf-89a9-42fa-88bf-ce2a470a8618)

**Comment by DaddyLazarus** [comment]
It is not a trojan, compiled python scripts almost always present false positives. If you have your doubts with the executable, just use the source code. However, I don't believe the tool still works regardless. I haven't updated it basically since I've made it and I no longer use discord so I'm unaware of any changes they may have made in the past 3 years.
